name: Publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install wheel
      run: python -m pip install wheel twine
    - name: Build a binary wheel and a source tarball
      run: python setup.py bdist_wheel
    - name: Publish distribution ğŸ“¦ to Test PyPI
      env:
        password: ${{ secrets.test_pypi_password }}
      run: python -m twine upload --repository_url https://test.pypi.org/legacy/ dist/* -u senseye -p "${password}"
      # run: python -m twine upload dist/*
      # with:
      #   username: senseye
      #   password: ${{ secrets.test_pypi_password }}
      #   repository_url: https://test.pypi.org/legacy/
    # - name: Publish distribution ğŸ“¦ to PyPI
    #   if: startsWith(github.event.ref, 'refs/tags')
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     password: ${{ secrets.pypi_password }}
